### ISSUE TITLE
当把get_problem_source()里的language 换成其他语言时会生成空白文件

### ISSUE THREAD

**Issue by cyct123** [zhtwd/lctool#2]
问题出在fun.py的66 - 78行，在运行`codesj = [cj + '}' if not cj.endswith('}') else '{' + cj for cj in codesj]`时，除了头尾两个cj可以正常存进codeinfo这个dict中，中间cj存进去的都为空。
因为在进行`if not cj.endswith('}')`判断时，中间的cj既不是以'{'开头,也不是以'}'结尾，没有在'{}'中，所以就没有存进codeinfo这个dict中。
我的解决方法是将给cj添加'{}'的过程写在`js = str(cj).replace("'", "\"")`之前，用`if cj.endswith('}')`和`cj.startswith('{')`给头尾两个cj添加'{'或'}'，剩下的cj再在头尾添加'{'和'}'。`cj = '{' + cj + '}'`

**Comment by zhtwd** [comment]
多谢 修改了 可以pull request一起改进这个小工具

**Comment by zhtwd** [comment]
先close这个issue 有问题可以重新开启
