### ISSUE TITLE
downloading python version

### ISSUE THREAD

**Issue by nkukarl** [zhtwd/lctool#3]
One issue is file extension name:
In run.py, line 29 `filepath += '.' + lang` shall be updated to
`if lang == 'python':
    filepath += '.py'
else:
    filepath += '.' + lang`

Seems similar issues exist for javascript (have not fully tested it).

Another issue is the symbols used for comments:
'/_' and '_/' were used no matter what programming language was chosen.
They both shall be changed to '"""' for python files.

Besides, it might be helpful to include a detailed instruction on how to change language in func.py.
We can discuss.

**Comment by zhtwd** [comment]
Thanks! Actually this tool is not fully supporting other languages. I'm working on it. I merged your pull request for python temporally, it will be great if you could design it for all languages. Please share with me more ideas if you can :)

**Comment by zhtwd** [comment]
Improved it. Close it for now.
