### ISSUE TITLE
error occured

### ISSUE THREAD

**Issue by fengzhyuan** [zhtwd/lctool#6]
hi, I met an error when tried to run the command:
**lc-submit -p ./array/3sum.cpp** 

error detail:
**output:**
Traceback (most recent call last):
  File "/usr/local/bin/lc-submit", line 9, in <module>
    load_entry_point('lctool==0.1.0.dev0', 'console_scripts', 'lc-submit')()
  File "build/bdist.linux-x86_64/egg/lctool/run.py", line 60, in submit
  File "build/bdist.linux-x86_64/egg/lctool/func.py", line 106, in submit_problem
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 741, in json
    return json.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**env:** ubuntu 14.04 python 2.7

**source code**: func.py line 103, tmp return state 405; line 105 midres1 return state 405

**Comment by Rouen007** [comment]
When I input the instruction: "lc-get", I get the error message: 
"Traceback (most recent call last):
  File "/Users/rouen/anaconda/bin/lc-get", line 9, in <module>
    load_entry_point('lctool==0.1.0.dev0', 'console_scripts', 'lc-get')()
  File "build/bdist.macosx-10.5-x86_64/egg/lctool/run.py", line 37, in lcget
  File "build/bdist.macosx-10.5-x86_64/egg/lctool/func.py", line 63, in get_problem_source
KeyError: 'ng-init'"
So I have no idea what to do.

**Comment by voidense** [comment]
It looks like leetcode.com has updated its website with some new elements and also the html structure, my guess is @Rouen007 installed lctool after this update and could not even get lc-get to run (ng-init is an Angular JS directive) while @fengzhyuan got all problems local before this update, so he fails to submit right now. We have to contact the author @zhtwd to figure this out.

**Comment by zhtwd** [comment]
Thanks! I'll have a look.

**Comment by voidense** [comment]
Hi @zhtwd , any update for this issue?

Update: @zhtwd , never mind, checkout my latest pull request.

**Comment by zhtwd** [comment]
@enirinth I merged your latest pull request. Thanks! The /submit also return 403 with current code, any idea?

**Comment by voidense** [comment]
@zhtwd I know basically nothing about angular, some random guesses here (ignore me if I'm wrong): the "submit solution" button is registered against aceCtrl.interpret.submitCode(), while definition of submitCode() is nowhere to find in the web page source code. I guess it was previously defined explicitly as a http request to an explicit url and now they change their mind and hide this web API?

I'm happy with getting all the problem source codes for now :)

**Comment by zhtwd** [comment]
@enirinth Thank you for investigating! I made a temporary fix for the lc-submit, please test if it works for you.

**Comment by voidense** [comment]
@zhtwd  Cool, working now. Thanks for the fix. Hope they won't update their website frequently.
